package hub

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"ph01-experience-hub/internal/governance"
)

var (
	ErrMissingPackageZip    = errors.New("experience package missing package.zip")
	ErrMissingPublisherJSON = errors.New("experience package missing publisher.json")
	ErrMissingRatingsDat    = errors.New("experience package missing ratings.dat")
	ErrInvalidPackageZip    = errors.New("package.zip must be a valid zip archive")
)

type PackageInfo struct {
	Manifest      Manifest
	PackageData   []byte
	PublisherData []byte
	RatingsData   []byte
	RawPath       string
}

type PublisherInfo struct {
	SchemaVersion        string `json:"schema_version,omitempty"`
	ExperienceID         string `json:"experience_id,omitempty"`
	PackageHashAlgorithm string `json:"package_hash_algorithm,omitempty"`
	PackageHash          string `json:"package_hash,omitempty"`
	PublisherPubkey      string `json:"publisher_pubkey,omitempty"`
	PublisherPubkeyHash  string `json:"publisher_pubkey_hash,omitempty"`
	SignatureAlgorithm   string `json:"signature_algorithm,omitempty"`
	Signature            string `json:"signature,omitempty"`
	CreatedAt            string `json:"created_at,omitempty"`
}

func PackDir(dir string) ([]byte, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if strings.HasPrefix(rel, "../") || rel == ".." {
			return errors.New("path escapes package dir")
		}
		w, err := zw.Create(rel)
		if err != nil {
			return err
		}
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()
		_, err = io.Copy(w, f)
		return err
	})
	if closeErr := zw.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func PackExperiencePackage(rawDir string, publisherJSON, ratingsData []byte) ([]byte, error) {
	packageData, err := PackDir(rawDir)
	if err != nil {
		return nil, err
	}
	if len(publisherJSON) == 0 {
		publisherJSON, err = json.MarshalIndent(map[string]string{
			"status":     "draft",
			"created_at": nowRFC3339(),
			"note":       "unsigned local package generated by ph01-expctl",
		}, "", "  ")
		if err != nil {
			return nil, err
		}
	}

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, entry := range []struct {
		name string
		data []byte
	}{
		{name: "package.zip", data: packageData},
		{name: "publisher.json", data: publisherJSON},
		{name: "ratings.dat", data: ratingsData},
	} {
		w, err := zw.Create(entry.name)
		if err != nil {
			_ = zw.Close()
			return nil, err
		}
		if _, err := w.Write(entry.data); err != nil {
			_ = zw.Close()
			return nil, err
		}
	}
	if err := zw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func ReadManifest(zipData []byte) (*Manifest, error) {
	info, err := ReadPackageInfo(zipData)
	if err != nil {
		return nil, err
	}
	return &info.Manifest, nil
}

func ReadPackageInfo(zipData []byte) (*PackageInfo, error) {
	r, err := zip.NewReader(bytes.NewReader(zipData), int64(len(zipData)))
	if err != nil {
		return nil, err
	}
	var (
		packageData   []byte
		publisherData []byte
		ratingsData   []byte
	)
	for _, f := range r.File {
		name := cleanZipName(f.Name)
		switch name {
		case "package.zip":
			rc, err := f.Open()
			if err != nil {
				return nil, err
			}
			packageData, err = io.ReadAll(rc)
			rc.Close()
			if err != nil {
				return nil, err
			}
		case "publisher.json":
			rc, err := f.Open()
			if err != nil {
				return nil, err
			}
			publisherData, err = io.ReadAll(rc)
			rc.Close()
			if err != nil {
				return nil, err
			}
		case "ratings.dat":
			rc, err := f.Open()
			if err != nil {
				return nil, err
			}
			ratingsData, err = io.ReadAll(rc)
			rc.Close()
			if err != nil {
				return nil, err
			}
		}
	}
	if len(packageData) == 0 {
		return nil, ErrMissingPackageZip
	}
	if len(publisherData) == 0 {
		return nil, ErrMissingPublisherJSON
	}
	if ratingsData == nil {
		return nil, ErrMissingRatingsDat
	}
	if _, err := zip.NewReader(bytes.NewReader(packageData), int64(len(packageData))); err != nil {
		return nil, ErrInvalidPackageZip
	}

	manifest, rawPath, err := readInnerMetadata(packageData)
	if err != nil {
		return nil, err
	}
	hash := sha256.Sum256(packageData)
	hashHex := fmt.Sprintf("%x", hash[:])
	publisher, _ := DecodePublisherInfo(publisherData)
	if strings.TrimSpace(manifest.ExperienceID) == "" {
		manifest.ExperienceID = "exp_" + hashHex[:16]
	}
	if strings.TrimSpace(manifest.Title) == "" {
		manifest.Title = manifest.ExperienceID
	}
	manifest.ContentHash = hashHex
	if strings.TrimSpace(manifest.PublisherPubkey) == "" {
		manifest.PublisherPubkey = publisher.PublisherPubkey
	}
	return &PackageInfo{
		Manifest:      manifest,
		PackageData:   packageData,
		PublisherData: publisherData,
		RatingsData:   ratingsData,
		RawPath:       rawPath,
	}, nil
}

func DecodePublisherInfo(data []byte) (PublisherInfo, error) {
	var publisher PublisherInfo
	if len(data) == 0 {
		return publisher, ErrMissingPublisherJSON
	}
	if err := json.Unmarshal(data, &publisher); err != nil {
		return publisher, err
	}
	return publisher, nil
}

func VerifyPublisherInfo(publisher PublisherInfo, packageHash string) error {
	if strings.TrimSpace(publisher.ExperienceID) == "" {
		return errors.New("publisher.json missing experience_id")
	}
	if publisher.PackageHashAlgorithm != "" && publisher.PackageHashAlgorithm != "sha256" {
		return errors.New("publisher.json package_hash_algorithm unsupported")
	}
	if !strings.EqualFold(strings.TrimSpace(publisher.PackageHash), strings.TrimSpace(packageHash)) {
		return errors.New("publisher.json package_hash does not match package.zip")
	}
	if strings.TrimSpace(publisher.PublisherPubkey) == "" {
		return errors.New("publisher.json missing publisher_pubkey")
	}
	if publisher.SignatureAlgorithm != governance.Algorithm {
		return errors.New("publisher.json signature_algorithm unsupported")
	}
	if strings.TrimSpace(publisher.Signature) == "" {
		return errors.New("publisher.json missing signature")
	}
	payload := strings.Join([]string{
		"ph01.experience.publisher.v1",
		strings.TrimSpace(publisher.ExperienceID),
		strings.TrimSpace(packageHash),
		strings.TrimSpace(publisher.PublisherPubkey),
		strings.TrimSpace(publisher.CreatedAt),
	}, "\n")
	if err := governance.Verify(publisher.PublisherPubkey, []byte(payload), publisher.Signature); err != nil {
		return fmt.Errorf("verify publisher signature: %w", err)
	}
	return nil
}

func AddReviewMaterials(zipData, reviewMaterials []byte) ([]byte, error) {
	info, err := ReadPackageInfo(zipData)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, entry := range []struct {
		name string
		data []byte
	}{
		{name: "package.zip", data: info.PackageData},
		{name: "publisher.json", data: info.PublisherData},
		{name: "ratings.dat", data: info.RatingsData},
		{name: "review-materials.json", data: reviewMaterials},
	} {
		w, err := zw.Create(entry.name)
		if err != nil {
			_ = zw.Close()
			return nil, err
		}
		if _, err := w.Write(entry.data); err != nil {
			_ = zw.Close()
			return nil, err
		}
	}
	if err := zw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func ExtractZip(zipData []byte, dest string) error {
	r, err := zip.NewReader(bytes.NewReader(zipData), int64(len(zipData)))
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dest, 0o755); err != nil {
		return err
	}
	for _, f := range r.File {
		name := cleanZipName(f.Name)
		if name == "" {
			continue
		}
		target := filepath.Join(dest, filepath.FromSlash(name))
		if !pathInside(dest, target) {
			return errors.New("zip entry escapes destination: " + f.Name)
		}
		if f.FileInfo().IsDir() {
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		rc, err := f.Open()
		if err != nil {
			return err
		}
		out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
		if err != nil {
			rc.Close()
			return err
		}
		_, copyErr := io.Copy(out, rc)
		closeErr := out.Close()
		rc.Close()
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
	}
	return nil
}

func readInnerMetadata(packageData []byte) (Manifest, string, error) {
	r, err := zip.NewReader(bytes.NewReader(packageData), int64(len(packageData)))
	if err != nil {
		return Manifest{}, "", ErrInvalidPackageZip
	}
	var manifest Manifest
	rawPath := ""
	for _, f := range r.File {
		name := cleanZipName(f.Name)
		if name == "" || f.FileInfo().IsDir() {
			continue
		}
		if name == "metadata.json" {
			rc, err := f.Open()
			if err != nil {
				return Manifest{}, "", err
			}
			err = json.NewDecoder(rc).Decode(&manifest)
			rc.Close()
			if err != nil {
				return Manifest{}, "", err
			}
			continue
		}
		if rawPath == "" || rawPathPriority(name) < rawPathPriority(rawPath) {
			rawPath = name
		}
	}
	if rawPath != "" {
		rawPath = filepath.ToSlash(filepath.Join("content", rawPath))
	}
	return manifest, rawPath, nil
}

func rawPathPriority(name string) int {
	switch name {
	case "conversation.md", "raw/conversation.md":
		return 0
	case "events.md", "raw/events.md":
		return 1
	}
	if strings.HasSuffix(name, ".md") {
		return 2
	}
	if strings.HasSuffix(name, ".txt") {
		return 3
	}
	return 10
}

func cleanZipName(name string) string {
	name = filepath.ToSlash(strings.TrimSpace(name))
	name = strings.TrimPrefix(name, "/")
	name = filepath.ToSlash(filepath.Clean(name))
	if name == "." || strings.HasPrefix(name, "../") || name == ".." {
		return ""
	}
	return name
}

func pathInside(root, target string) bool {
	rootAbs, err := filepath.Abs(root)
	if err != nil {
		return false
	}
	targetAbs, err := filepath.Abs(target)
	if err != nil {
		return false
	}
	rel, err := filepath.Rel(rootAbs, targetAbs)
	if err != nil {
		return false
	}
	return rel == "." || (!strings.HasPrefix(rel, ".."+string(filepath.Separator)) && rel != "..")
}
