package hub

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

var (
	ErrMissingPackageZip    = errors.New("experience package missing package.zip")
	ErrMissingPublisherJSON = errors.New("experience package missing publisher.json")
	ErrMissingRatingsDat    = errors.New("experience package missing ratings.dat")
	ErrInvalidPackageZip    = errors.New("package.zip must be a valid zip archive")
)

type PackageInfo struct {
	Manifest    Manifest
	PackageData []byte
	RawPath     string
}

func PackDir(dir string) ([]byte, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if strings.HasPrefix(rel, "../") || rel == ".." {
			return errors.New("path escapes package dir")
		}
		w, err := zw.Create(rel)
		if err != nil {
			return err
		}
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()
		_, err = io.Copy(w, f)
		return err
	})
	if closeErr := zw.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func PackExperiencePackage(rawDir string, publisherJSON, ratingsData []byte) ([]byte, error) {
	packageData, err := PackDir(rawDir)
	if err != nil {
		return nil, err
	}
	if len(publisherJSON) == 0 {
		publisherJSON, err = json.MarshalIndent(map[string]string{
			"status":     "draft",
			"created_at": nowRFC3339(),
			"note":       "unsigned local package generated by ph01-expctl",
		}, "", "  ")
		if err != nil {
			return nil, err
		}
	}

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, entry := range []struct {
		name string
		data []byte
	}{
		{name: "package.zip", data: packageData},
		{name: "publisher.json", data: publisherJSON},
		{name: "ratings.dat", data: ratingsData},
	} {
		w, err := zw.Create(entry.name)
		if err != nil {
			_ = zw.Close()
			return nil, err
		}
		if _, err := w.Write(entry.data); err != nil {
			_ = zw.Close()
			return nil, err
		}
	}
	if err := zw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func ReadManifest(zipData []byte) (*Manifest, error) {
	info, err := ReadPackageInfo(zipData)
	if err != nil {
		return nil, err
	}
	return &info.Manifest, nil
}

func ReadPackageInfo(zipData []byte) (*PackageInfo, error) {
	r, err := zip.NewReader(bytes.NewReader(zipData), int64(len(zipData)))
	if err != nil {
		return nil, err
	}
	var (
		packageData  []byte
		hasPublisher bool
		hasRatings   bool
	)
	for _, f := range r.File {
		name := cleanZipName(f.Name)
		switch name {
		case "package.zip":
			rc, err := f.Open()
			if err != nil {
				return nil, err
			}
			packageData, err = io.ReadAll(rc)
			rc.Close()
			if err != nil {
				return nil, err
			}
		case "publisher.json":
			hasPublisher = true
		case "ratings.dat":
			hasRatings = true
		}
	}
	if len(packageData) == 0 {
		return nil, ErrMissingPackageZip
	}
	if !hasPublisher {
		return nil, ErrMissingPublisherJSON
	}
	if !hasRatings {
		return nil, ErrMissingRatingsDat
	}
	if _, err := zip.NewReader(bytes.NewReader(packageData), int64(len(packageData))); err != nil {
		return nil, ErrInvalidPackageZip
	}

	manifest, rawPath, err := readInnerMetadata(packageData)
	if err != nil {
		return nil, err
	}
	hash := sha256.Sum256(packageData)
	hashHex := fmt.Sprintf("%x", hash[:])
	if strings.TrimSpace(manifest.ExperienceID) == "" {
		manifest.ExperienceID = "exp_" + hashHex[:16]
	}
	if strings.TrimSpace(manifest.Title) == "" {
		manifest.Title = manifest.ExperienceID
	}
	manifest.ContentHash = hashHex
	return &PackageInfo{
		Manifest:    manifest,
		PackageData: packageData,
		RawPath:     rawPath,
	}, nil
}

func ExtractZip(zipData []byte, dest string) error {
	r, err := zip.NewReader(bytes.NewReader(zipData), int64(len(zipData)))
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dest, 0o755); err != nil {
		return err
	}
	for _, f := range r.File {
		name := cleanZipName(f.Name)
		if name == "" {
			continue
		}
		target := filepath.Join(dest, filepath.FromSlash(name))
		if !pathInside(dest, target) {
			return errors.New("zip entry escapes destination: " + f.Name)
		}
		if f.FileInfo().IsDir() {
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		rc, err := f.Open()
		if err != nil {
			return err
		}
		out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
		if err != nil {
			rc.Close()
			return err
		}
		_, copyErr := io.Copy(out, rc)
		closeErr := out.Close()
		rc.Close()
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
	}
	return nil
}

func readInnerMetadata(packageData []byte) (Manifest, string, error) {
	r, err := zip.NewReader(bytes.NewReader(packageData), int64(len(packageData)))
	if err != nil {
		return Manifest{}, "", ErrInvalidPackageZip
	}
	var manifest Manifest
	rawPath := ""
	for _, f := range r.File {
		name := cleanZipName(f.Name)
		if name == "" || f.FileInfo().IsDir() {
			continue
		}
		if name == "metadata.json" {
			rc, err := f.Open()
			if err != nil {
				return Manifest{}, "", err
			}
			err = json.NewDecoder(rc).Decode(&manifest)
			rc.Close()
			if err != nil {
				return Manifest{}, "", err
			}
			continue
		}
		if rawPath == "" || rawPathPriority(name) < rawPathPriority(rawPath) {
			rawPath = name
		}
	}
	if rawPath != "" {
		rawPath = filepath.ToSlash(filepath.Join("content", rawPath))
	}
	return manifest, rawPath, nil
}

func rawPathPriority(name string) int {
	switch name {
	case "conversation.md", "raw/conversation.md":
		return 0
	case "events.md", "raw/events.md":
		return 1
	}
	if strings.HasSuffix(name, ".md") {
		return 2
	}
	if strings.HasSuffix(name, ".txt") {
		return 3
	}
	return 10
}

func cleanZipName(name string) string {
	name = filepath.ToSlash(strings.TrimSpace(name))
	name = strings.TrimPrefix(name, "/")
	name = filepath.ToSlash(filepath.Clean(name))
	if name == "." || strings.HasPrefix(name, "../") || name == ".." {
		return ""
	}
	return name
}

func pathInside(root, target string) bool {
	rootAbs, err := filepath.Abs(root)
	if err != nil {
		return false
	}
	targetAbs, err := filepath.Abs(target)
	if err != nil {
		return false
	}
	rel, err := filepath.Rel(rootAbs, targetAbs)
	if err != nil {
		return false
	}
	return rel == "." || (!strings.HasPrefix(rel, ".."+string(filepath.Separator)) && rel != "..")
}
